name: Sign Guestbook
description: Leave a friendly message on my profile!
title: "Guestbook Sign: <Your Name>"
labels: ["guestbook"]
body:
  - type: textarea
    id: message
    attributes:
      label: Message
      description: What message would you like to leave?
      placeholder: "Hi Ahmed, nice profile!"
    validations:
      required: true
